workspace:
  base: /drone/src
  path: vaadin-developer-demo-vaadin-selenium

pipeline:
  build:
    image: ${JDK_VERSION}
    pull: true
    environment:
#      - IP_NEXUS=172.17.0.5
    commands:
      - mkdir /root/.m2
      - cp /drone/src/vaadin-developer-demo-vaadin-selenium/_data/nexus/settings.xml /root/.m2/settings.xml
      - mvn clean
      - mvn install

matrix:
  JDK_VERSION:
  - maven:latest
  - maven:3.5-jdk-8-alpine
  - maven:3.5-jdk-9
  - svenruppert/maven-3.5-jdk-10
  - maven:3.5-ibmjava-8
  - maven:3.5-ibmjava-9
  - maven:3.5-jdk-8
  - maven:3.5-jdk-8-slim
  - maven:3.5-ibmjava-8-alpine
  - maven:3.5-ibmjava-9-alpine

#services:
#  docker:
#    image: docker:dind
##    command: [ "--storage-driver=vfs", "--tls=false" ]
#+   privileged: true


#docker run -d --name=bind --dns=127.0.0.1 \
#  --publish=192.168.0.228:53:53/udp --publish=192.168.0.228:10000:10000 \
#  --env='ROOT_PASSWORD=root' \
#  sameersbn/bind:latest

#docker run -d --name=bind --dns=127.0.0.1 \
#  --publish=53:53/udp --publish=172.17.42.1:10000:10000 \
#  --env='ROOT_PASSWORD=root' \
#  sameersbn/bind:latest

  #  --volume=/srv/docker/bind:/data \
