workspace:
  base: /drone/src
  path: vaadin-developer-demo-vaadin-selenium

pipeline:
  build:
    image: ${JDK_VERSION}
    pull: true
    environment:
#      - IP_NEXUS=172.17.0.5
    commands:
      - mkdir /root/.m2
      - cp /drone/src/vaadin-developer-demo-vaadin-selenium/_data/nexus/settings.xml /root/.m2/settings.xml
      - mvn clean
      - mvn install

matrix:
  JDK_VERSION:
  - svenruppert/maven-3.5-jdk-08
  - svenruppert/maven-3.5-jdk-09
  - svenruppert/maven-3.5-jdk-10
  - svenruppert/maven-3.5-jdk-oracle-09
  - svenruppert/maven-3.5-jdk-zulu-08
  - svenruppert/maven-3.5-jdk-zulu-09
  - maven:3.5-ibmjava-8-alpine
#  - maven:3.5-ibmjava-9-alpine


