workspace:
  base: /drone/src
  path: vaadin-developer-demo-vaadin-selenium

pipeline:
  build:
    image: maven:${JDK_VERSION}
#    image: maven:3.5-jdk-8
    pull: true
    environment:
      - IP_NEXUS=172.17.0.5
#      - IP_SELENOID=172.17.0.3
    commands:
      - mkdir /root/.m2
      - cp /drone/src/vaadin-developer-demo-vaadin-selenium/settings.xml /root/.m2/settings.xml
      - mvn clean
      - mvn -DIP_SELENOID=172.17.0.3 install

matrix:
  JDK_VERSION:
#  - latest
  - 3.5-jdk-8
#  - 3.5-jdk-8-alpine
#  - 3.5-jdk-8-slim
#  - 3.5-ibmjava-8 # missing jdeps ;-)
#  - 3.5-jdk-9

#services:
#  docker:
#    image: docker:dind
##    command: [ "--storage-driver=vfs", "--tls=false" ]
#+   privileged: true